services:
  electricpanel-app:
    image: electricpanel
    container_name: electricpanel-app
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      MONGODB_URI: # TODO: Add MongoDB URI
      STEAM_API_KEY: # TODO: Add Steam API Key
      DATABASE_URL_1: # TODO: Add Database URL 1
      DATABASE_URL_2: # TODO: Add Database URL 2
    ports:
      - '3000:3000'
    restart: unless-stopped
